/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CariRouteImport } from './routes/cari'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as TamatRouteImport } from './routes/tamat'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DownloadBatchIdRouteImport } from './routes/download/$batchId'
import { Route as GenreIndexRouteImport } from './routes/genre/index'
import { Route as GenreGenreIdRouteImport } from './routes/genre/$genreId'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch/$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CariRoute = CariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const TamatRoute = TamatRouteImport.update({
  id: '/tamat',
  path: '/tamat',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadBatchIdRoute = DownloadBatchIdRouteImport.update({
  id: '/download/$batchId',
  path: '/download/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreIndexRoute = GenreIndexRouteImport.update({
  id: '/genre/',
  path: '/genre/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreIdRoute = GenreGenreIdRouteImport.update({
  id: '/genre/$genreId',
  path: '/genre/$genreId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/jadwal': typeof JadwalRoute
  '/notifikasi': typeof NotifikasiRoute
  '/ongoing': typeof OngoingRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tamat': typeof TamatRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/download/$batchId': typeof DownloadBatchIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/download/': typeof DownloadIndexRoute
  '/genre/': typeof GenreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/jadwal': typeof JadwalRoute
  '/notifikasi': typeof NotifikasiRoute
  '/ongoing': typeof OngoingRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tamat': typeof TamatRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/download/$batchId': typeof DownloadBatchIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/download': typeof DownloadIndexRoute
  '/genre': typeof GenreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cari': typeof CariRoute
  '/jadwal': typeof JadwalRoute
  '/notifikasi': typeof NotifikasiRoute
  '/ongoing': typeof OngoingRoute
  '/profil': typeof ProfilRoute
  '/riwayat': typeof RiwayatRoute
  '/tamat': typeof TamatRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/download/$batchId': typeof DownloadBatchIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/download/': typeof DownloadIndexRoute
  '/genre/': typeof GenreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cari'
    | '/jadwal'
    | '/notifikasi'
    | '/ongoing'
    | '/profil'
    | '/riwayat'
    | '/tamat'
    | '/watchlist'
    | '/anime/$animeId'
    | '/download/$batchId'
    | '/genre/$genreId'
    | '/watch/$episodeId'
    | '/download/'
    | '/genre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cari'
    | '/jadwal'
    | '/notifikasi'
    | '/ongoing'
    | '/profil'
    | '/riwayat'
    | '/tamat'
    | '/watchlist'
    | '/anime/$animeId'
    | '/download/$batchId'
    | '/genre/$genreId'
    | '/watch/$episodeId'
    | '/download'
    | '/genre'
  id:
    | '__root__'
    | '/'
    | '/cari'
    | '/jadwal'
    | '/notifikasi'
    | '/ongoing'
    | '/profil'
    | '/riwayat'
    | '/tamat'
    | '/watchlist'
    | '/anime/$animeId'
    | '/download/$batchId'
    | '/genre/$genreId'
    | '/watch/$episodeId'
    | '/download/'
    | '/genre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CariRoute: typeof CariRoute
  JadwalRoute: typeof JadwalRoute
  NotifikasiRoute: typeof NotifikasiRoute
  OngoingRoute: typeof OngoingRoute
  ProfilRoute: typeof ProfilRoute
  RiwayatRoute: typeof RiwayatRoute
  TamatRoute: typeof TamatRoute
  WatchlistRoute: typeof WatchlistRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  DownloadBatchIdRoute: typeof DownloadBatchIdRoute
  GenreGenreIdRoute: typeof GenreGenreIdRoute
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  GenreIndexRoute: typeof GenreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari': {
      id: '/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof CariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamat': {
      id: '/tamat'
      path: '/tamat'
      fullPath: '/tamat'
      preLoaderRoute: typeof TamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$batchId': {
      id: '/download/$batchId'
      path: '/download/$batchId'
      fullPath: '/download/$batchId'
      preLoaderRoute: typeof DownloadBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/': {
      id: '/genre/'
      path: '/genre'
      fullPath: '/genre/'
      preLoaderRoute: typeof GenreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genreId': {
      id: '/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof GenreGenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CariRoute: CariRoute,
  JadwalRoute: JadwalRoute,
  NotifikasiRoute: NotifikasiRoute,
  OngoingRoute: OngoingRoute,
  ProfilRoute: ProfilRoute,
  RiwayatRoute: RiwayatRoute,
  TamatRoute: TamatRoute,
  WatchlistRoute: WatchlistRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  DownloadBatchIdRoute: DownloadBatchIdRoute,
  GenreGenreIdRoute: GenreGenreIdRoute,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  GenreIndexRoute: GenreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
